FROM python:3.11-slim

RUN apt-get update && apt-get install -y \
    gcc \
    default-libmysqlclient-dev \
    pkg-config \
    build-essential \
    git \
    bzip2 \
    apt-utils && \
    rm -rf /var/lib/apt/lists/*

WORKDIR /app

RUN git clone https://github.com/nikhilvyamsani/MyAttendance.git .

RUN pip install --no-cache-dir -r requirements.txt

EXPOSE 8501

CMD ["streamlit", "run", "app.py", "--server.port=8501", "--server.headless=true"]
